### ISSUE TITLE
dart 

### ISSUE THREAD

**Issue by adam-singer** [rcn-ee/repos#1]
would it be possible to package the full dart sdk in a deb file? After talking with some dart folks stuff build system should support building full arm sdk. `$ ./tools/build.py -m release -a arm create_sdk`

**Comment by sebe** [comment]
Now that rpi 2 is armv7, could you please try again, ./tools/build.py -m release -a arm create_sdk, very disappointing that there is no pub in your current deb.

**Comment by RobertCNelson** [comment]
@sebe i've been building on "armv7" from the start.  Now that you can get a armv7/rpi2 you can help debug the segfaults too.. ;)  None repo/public *.deb's are located here: http://repos.rcn-ee.net/archive/

**Comment by jadonk** [comment]
Is this still an issue?

**Comment by RobertCNelson** [comment]
We just ship the dart run time..

The full blown sdk with eclipse ide, they'll have to install on an x86 system..

Regards,
