### ISSUE TITLE
Update to bonescript-0.5.0-beta6

### ISSUE THREAD

**Issue by jadonk** [rcn-ee/repos#11]
Untested fix for getPlatform() function to work with 4.4 kernels.

**Comment by jadonk** [comment]
@RobertCNelson @Pillar1989 I've noticed the latest snapshot still doesn't have this update. It causes the getPlatform() function to break as you can see on the bone101 pages where you don't get the board info.

**Comment by RobertCNelson** [comment]
https://github.com/Pillar1989/wifidog-server/blob/BBGW/package.json#L9

What's the trick to define the latest..

**Comment by jadonk** [comment]
Oh, right, I forgot there were 2 copies.

According to http://semver.npmjs.com/, "^0.5.0-beta5" should have included 0.5.0-beta6 as a possible option, but I don't know if npm decides to use the latest or first one in the range. You could always try simply using "beta" to grab the one that currently has the beta tag.

**Comment by jadonk** [comment]
What about beta9 along with setting SERVER_DIR=/usr/share/bone101?
