### ISSUE TITLE
libsigrok, libsigrokdecode, sigrok-cli , pulseview

### ISSUE THREAD

**Issue by RobertCNelson** [rcn-ee/repos#3]
<Abhishek_> rcn-ee: Would you be able to distribute built packages for libsigrok, libsigrokdecode, sigrok-cli and pulseview for armhf (BeagleBone Black) compiled from their respective git sources

**Comment by jadonk** [comment]
Is this not already part of Jessie?
* https://packages.debian.org/jessie/libsigrok-dev
* https://packages.debian.org/jessie/libsigrokdecode-dev
* https://packages.debian.org/jessie/sigrok-cli
* https://packages.debian.org/jessie/pulseview

Is this version new enough to have the PRU support?

**Comment by RobertCNelson** [comment]
All merged in...  Please test... i've added these to my package checker, so as newer version go to sid, they'll be backportred..
