### ISSUE TITLE
after setting TETHER_ENABLED=no or USE_CONNMAN_TETHER=yes dnsmasq is not started

### ISSUE THREAD

**Issue by vvavrychuk** [rcn-ee/repos#32]
I am using Debian 9.2 2017-10-10 IoT on Beagle Bone Black Wireless. If I set mentioned parameters I get no dnsmasq started. This means that ethernet-over-usb interfaces will not get 192.168.6.1 and 192.168.7.1 addresses. Instead they obtain some link-local IP addresses. This means that it is not possible to connect to the board over SSH using method described in documentation.

**Comment by RobertCNelson** [comment]
That is correct, change the defaults and you need to configure things yourself. Closing..
