### ISSUE TITLE
Cloud9 won't start without /var/lib/cloud9 folder on Jessie

### ISSUE THREAD

**Issue by BrianAdams** [rcn-ee/repos#4]
After doing a clean install on the route image using the c9-core-installer package, trying to connect to the service which is doing socket activation fails to start the cloud9 service:

● cloud9.service - Cloud9 IDE
   Loaded: loaded (/etc/systemd/system/cloud9.service; static)
   Active: inactive (dead)
           start condition failed at Mon 2015-06-29 19:01:30 UTC; 44ms ago
           none of the trigger conditions were met

The condition is the requirement that the /var/lib/cloud9 folder exists.  If I manually create the folder the system will start.

**Comment by RobertCNelson** [comment]
So, normally, /var/lib/cloud9 is a git repo pointing to https://github.com/beagleboard/bone101
I guess, we could have the package "mkdir -p /var/lib/cloud9", but i probally won't have it auto-git-clone the bone101 repo...
