### ISSUE TITLE
Provide an upgraded deb image for npm to go with the Node4 upgraded deb?

### ISSUE THREAD

**Issue by BrianAdams** [rcn-ee/repos#5]
with Node 4, npm install on our application throws all kinds of 'value not escaped errors'. After researching, it turns out upgrading to a more recent version of npm solves the issue.  Could have something to do with our image running Jessie 8.3.  Could be the node 4 upgrade. Don't know.

I'm assuming the node installation does not include npm.  If it does I'll remove the apt-get of the npm package from our build config to work around.

Assuming I'm not paving over a more recent version of npm with the deb file installed version...

Any issue with including the current version of NPM  in the node experiment repo to be installed along side the new node version?  When running the omap-image build we end up pulling the npm 1.4.21 which seems to be coming from the standard debian repos.

Upgrading to npm 3.7.1 worked for us.

**Comment by RobertCNelson** [comment]
Hi @BrianAdams i've tempted to just do:

```
sudo npm install npm -g
```

as there's been no movement on:
https://packages.qa.debian.org/n/npm.html

and we already just install the latest version of pip:

https://github.com/RobertCNelson/omap-image-builder/blob/master/target/chroot/beagleboard.org-jessie.sh#L227-L251

Regards,

**Comment by BrianAdams** [comment]
As a debian package install command?  That would work.

**Comment by RobertCNelson** [comment]
Running on test builder:
http://rcn-ee.homeip.net:8080/job/omap-image-builder_testrun/24/console

so we will see what happens. ;)

Regards,

**Comment by RobertCNelson** [comment]
Err, try again,

http://rcn-ee.homeip.net:8080/job/omap-image-builder_testrun/25/console

Didn't pickup the new binary...
Regards,
