### ISSUE TITLE
generic-sys-mods post install script broken

### ISSUE THREAD

**Issue by cozzyd** [rcn-ee/repos#67]
Putting this here because the comment I posted (https://github.com/rcn-ee/repos/commit/eded7e21d6d9051c45a6b7fa1daa7e250ca3e5d5#r141532980 ) may not be too visible. 

Since profile no longer gets copied to /etc/bbb.io/templates, the post install script breaks because it can't copy.

**Comment by RobertCNelson** [comment]
Thanks @cozzyd sorry about this, we can just remove the profile.  fixing now..

**Comment by RobertCNelson** [comment]
and pushed out bookworm updated.. biggest change was a merge for all the UK/EU cyber rules changes..

https://openbeagle.org/beagleboard/bbbio-set-sysconf/-/blob/main/src/debian/sysconf.txt?ref_type=heads

i still need to split out the single ext4 to a fat + ext4 for end user customizations..

**Comment by cozzyd** [comment]
thanks for the very quick fix! Appreciate all the work you do.
