### ISSUE TITLE
Debian wheezy v7.9

### ISSUE THREAD

**Issue by OmarHallab** [rcn-ee/repos#7]
Hi, 

I am currently developing on a beaglebone board with wheezy-debian v7.9 installed, my version of node.js is 0.10.42 & I require to have 0.12.0. 

Are there any limitation regarding the OS (Debian wheezy) in order to perform nodejs update to 0.12.0? 

I have followed the repo, as everytime i call: 

curl -sL https://deb.nodesource.com/setup_0.12 | sudo -E bash -
sudo apt-get install -y nodejs

It directs me to the v0.10.42 of this repo & performs the download .. 

..... 

Is there any way i can get my hands on nodejs v0.12.0 for debian wheezy v7.9? if so please fill me on how to do the update.

Thank you,
Omar
:)

**Comment by RobertCNelson** [comment]
Yeah:

```
curl -sL https://deb.nodesource.com/setup_0.12 | bash -
apt-get upgrade
apt-get install -y nodejs
```

Should work...

**Comment by OmarHallab** [comment]
Hi Rob,

I ran the following cmds , and it stated that "nodejs is already the newest version".

root@beaglebone:/home# node -v
v0.10.42

It just can't seem to perform the update ..

**Comment by RobertCNelson** [comment]
Okay, do it manual, as root:

```
apt-get install apt-transport-https
```
add the key:
```
wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
```
add the repo:
```
nano /etc/apt/sources.list

deb https://deb.nodesource.com/node_0.12 wheezy main
#deb-src https://deb.nodesource.com/node_0.12 wheezy main
```

Then, force the update:
```
apt-get update
apt-get dist-ugprade
```

**Comment by OmarHallab** [comment]
Hi Rob,

I've followed this guide & successfully installed node.js v0.12.0 on my Beaglebone Black
https://youtu.be/3HRceMZW7F4

Thanks,
Omar
